default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  database: <%= ENV['SHIDUR_DEV_DB'] %>
  username: <%= ENV['SHIDUR_DEV_USER'] %>
  password: <%= ENV['SHIDUR_DEV_PASS'] %>

test:
  <<: *default
  host: localhost
  database: <%= ENV['SHIDUR_TEST_DB'] %>
  username: <%= ENV['SHIDUR_TEST_USER'] %>
  password: <%= ENV['SHIDUR_TEST_PASS'] %>

production:
  <<: *default
  host: localhost
  database: <%= ENV['SHIDUR_PROD_DB'] %>
  username: <%= ENV['SHIDUR_PROD_USER'] %>
  password: <%= ENV['SHIDUR_PROD_PASS'] %>
